services:
  flemmarr:
    container_name: flemmarr
    image: pierremesure/flemmarr
    volumes:
      - ./config/flemmarr:/config/flemmarr/
    depends_on:
      - transmission
      - sonarr
      - radarr
      - lidarr
      - readarr
      - prowlarr
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/sonarr:/config/sonarr/
      - ~/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/radarr:/config/radarr/
      - ~/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  lidarr:
    container_name: lidarr
    image: linuxserver/lidarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/lidarr:/config/lidarr/
      - ~/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

  readarr:
    container_name: readarr
    image: linuxserver/readarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/readarr:/config/readarr/
      - ~/data:/data
    ports:
      - 8787:8787
    restart: unless-stopped

  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/prowlarr:/config/prowlarr/
    ports:
      - 9696:9696
    restart: unless-stopped

  transmission:
    container_name: transmission
    image: linuxserver/transmission
    environment:
      PUID: 1000
      PGID: 1000
      UMASK_SET: 022
      TZ: Europe/Stockholm
    volumes:
      - ~/config/transmission:/config/transmission/
      - ~/data/downloads/torrents:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
