sonarr:
  server:
    address: sonarr
    port: 8989
    apiKey: somerandom
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
    naming:
      renameEpisodes: true
      replaceIllegalCharacters: true
      multiEpisodeStyle: 5
      standardEpisodeFormat:
        "{Series TitleYear} - S{season:00}E{episode:00} - {Episode
        CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo
        AudioCodec}{ Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
        Group}"
      dailyEpisodeFormat:
        "{Series TitleYear} - {Air-Date} - {Episode CleanTitle} [{Preferred
        Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{
        Mediainfo AudioChannels]}{MediaInfo AudioLanguages}{[MediaInfo VideoCodec]}{-Release
        Group}"
      animeEpisodeFormat:
        "{Series TitleYear} - S{season:00}E{episode:00} - {absolute:000}
        - {Episode CleanTitle} [{Preferred Words }{Quality Full}]{[MediaInfo VideoDynamicRangeType]}[{MediaInfo
        VideoBitDepth}bit]{[MediaInfo VideoCodec]}[{Mediainfo AudioCodec} { Mediainfo AudioChannels}]{MediaInfo
        AudioLanguages}{-Release Group}"
      seriesFolderFormat: "{Series TitleYear} [imdb-{ImdbId}]"
      seasonFolderFormat: Season {season:00}
      specialsFolderFormat: Specials
      includeSeriesTitle: false
      includeEpisodeTitle: false
      includeQuality: false
      replaceSpaces: true
      separator: " - "
      numberStyle: S{season:00}E{episode:00}
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedEpisodes: false
      recycleBin: ""
      recycleBinCleanupDays: 7
      downloadPropersAndRepacks: doNotUpgrade
      createEmptySeriesFolders: false
      deleteEmptyFolders: false
      fileDate: none
      rescanAfterRefresh: always
      setPermissionsLinux: false
      chmodFolder: "755"
      chownGroup: ""
      episodeTitleRequired: always
      skipFreeSpaceCheckWhenImporting: true
      minimumFreeSpaceWhenImporting: 100
      copyUsingHardlinks: true
      importExtraFiles: true
      extraFileExtensions: srt
      enableMediaInfo: true
  rootfolder:
    - name: Downloads
      path: /Cloud/Downloads
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: Anime Series
      path: /Cloud/Anime/Series
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: Anime Movies
      path: /Cloud/Anime/Movies
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: TV Series
      path: /Cloud/TV/Series
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: TV Movies
      path: /Cloud/TV/Movies
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
  downloadclient:
    - name: qBittorrent
      enable: true
      protocol: torrent
      priority: 2
      removeCompletedDownloads: true
      removeFailedDownloads: true
      fields:
        - name: host
          value: qbittorrent
        - name: port
          value: 8080
        - name: username
          value: somerandom
        - name: password
          value: somerandom
        - name: tvCategory
          value: tv
        - name: recentTvPriority
          value: 0
        - name: olderTvPriority
          value: 0
        - name: initialState
          value: 0
        - name: sequentialOrder
          value: false
        - name: firstAndLast
          value: false
      implementation: QBittorrent
      configContract: QBittorrentSettings

radarr:
  server:
    address: radarr
    port: 7878
    apiKey: somerandom
  config:
    host:
      analyticsEnabled: false
    ui:
      firstDayOfWeek: 1 # 0 = Sunday, 1 = Monday
      timeFormat: HH:mm # HH:mm = 17:30, h(:mm)a = 5:30PM
      uiLanguage: 1 # 1 = English, 2 = French, 3 = Spanish...
    naming:
      renameMovies: true
      replaceIllegalCharacters: true
      colonReplacementFormat: spaceDashSpace
      # https://trash-guides.info/Radarr/Radarr-recommended-naming-scheme/
      standardMovieFormat: "{Movie CleanTitle} {(Release Year)} {imdb-{ImdbId}} {edition-{Edition Tags}} {[Custom Formats]}{[Quality Full]}{[MediaInfo 3D]}{[MediaInfo VideoDynamicRangeType]}{[Mediainfo AudioCodec}{ Mediainfo AudioChannels}][{Mediainfo VideoCodec}]{-Release Group}"
      movieFolderFormat: "{Movie CleanTitle} ({Release Year})"
      includeQuality: false
      replaceSpaces: false
    mediamanagement:
      autoUnmonitorPreviouslyDownloadedMovies: true
      recycleBin: ""
      recycleBinCleanupDays: 7
      downloadPropersAndRepacks: doNotUpgrade
      createEmptyMovieFolders: false
      deleteEmptyFolders: false
      fileDate: none
      rescanAfterRefresh: always
      autoRenameFolders: false
      pathsDefaultStatic: false
      setPermissionsLinux: false
      chmodFolder: "755"
      chownGroup: ""
      skipFreeSpaceCheckWhenImporting: true
      minimumFreeSpaceWhenImporting: 100
      copyUsingHardlinks: true
      importExtraFiles: true
      extraFileExtensions: srt
      enableMediaInfo: true
  rootfolder:
    - name: Downloads
      path: /Cloud/Downloads
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: Anime Series
      path: /Cloud/Anime/Series
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: Anime Movies
      path: /Cloud/Anime/Movies
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: TV Series
      path: /Cloud/TV/Series
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
    - name: TV Movies
      path: /Cloud/TV/Movies
      defaultTags: []
      defaultQualityProfileId: 1
      defaultMetadataProfileId: 1
  downloadclient:
    - name: qBittorrent
      enable: true
      protocol: torrent
      priority: 2
      removeCompletedDownloads: true
      removeFailedDownloads: true
      fields:
        - name: host
          value: qbittorrent
        - name: port
          value: 8080
        - name: username
          value: somerandom
        - name: password
          value: somerandom
        - name: tvCategory
          value: tv
        - name: recentTvPriority
          value: 0
        - name: olderTvPriority
          value: 0
        - name: initialState
          value: 0
        - name: sequentialOrder
          value: false
        - name: firstAndLast
          value: false
      implementation: QBittorrent
      configContract: QBittorrentSettings
